package com.encounter.mapper;

import com.encounter.bean.BsRfid;
import com.encounter.bean.BsRfidExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BsRfidMapper
    {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        long countByExample(BsRfidExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        int deleteByExample(BsRfidExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        int deleteByPrimaryKey(Integer id);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        int insert(BsRfid record);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        int insertSelective(BsRfid record);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        List<BsRfid> selectByExample(BsRfidExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        BsRfid selectByPrimaryKey(Integer id);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        int updateByExampleSelective(@Param("record") BsRfid record, @Param("example") BsRfidExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        int updateByExample(@Param("record") BsRfid record, @Param("example") BsRfidExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        int updateByPrimaryKeySelective(BsRfid record);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_rfid
         *
         * @mbg.generated
         */
        int updateByPrimaryKey(BsRfid record);
    }