package com.encounter.mapper;

import com.encounter.bean.BsVerdueRecord;
import com.encounter.bean.BsVerdueRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BsVerdueRecordMapper
    {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        long countByExample(BsVerdueRecordExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        int deleteByExample(BsVerdueRecordExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        int deleteByPrimaryKey(Integer id);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        int insert(BsVerdueRecord record);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        int insertSelective(BsVerdueRecord record);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        List<BsVerdueRecord> selectByExample(BsVerdueRecordExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        BsVerdueRecord selectByPrimaryKey(Integer id);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        int updateByExampleSelective(@Param("record") BsVerdueRecord record, @Param("example") BsVerdueRecordExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        int updateByExample(@Param("record") BsVerdueRecord record, @Param("example") BsVerdueRecordExample example);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        int updateByPrimaryKeySelective(BsVerdueRecord record);
        
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bs_verdue_record
         *
         * @mbg.generated
         */
        int updateByPrimaryKey(BsVerdueRecord record);
    }