metadata:
- appName: rams
  dataId: rams-dev.yaml
  desc: 毕设RAMS开发环境配置文件
  group: DEV
  type: yaml
- appName: ''
  dataId: shared-mysql.yaml
  desc: 共享MySQL配置
  group: SHARED
  type: yaml
- appName: ''
  dataId: shared-redis.yaml
  desc: redis共享配置
  group: SHARED
  type: yaml
- appName: ''
  dataId: shared-mybatis.yaml
  desc: mybatis共享配置
  group: SHARED
  type: yaml
- appName: ''
  dataId: shared-logs.yaml
  desc: logs日志共享配置
  group: SHARED
  type: yaml
- appName: rams
  dataId: rams-local.yaml
  desc: 毕设RAMS本地环境配置文件
  group: LOCAL
  type: yaml
- appName: rams
  dataId: rams-prod.yaml
  desc: 毕设RAMS生产环境配置文件
  group: PROD
  type: yaml
